# Operating system (build VM template)
os: Visual Studio 2015 CTP

environment:
  matrix:
    - VS_VERSION: MSVC2015

install:
  - set PATH=C:\Ruby25\bin;%PATH%

build_script:
  - curl -O https://curl.haxx.se/ca/cacert.pem
  - SET SSL_CERT_FILE=%cd%\cacert.pem

  - git submodule update --init --recursive
  - rm Gemfile.lock
  - bundle install --path bundle

  - cmake -G "MinGW Makefiles"
  - mingw32-make.exe all

test_script:
  - mingw32-make.exe test
  - bundle exec cucumber
